
project_id = "taswmdahpcubiyrgsjki"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
enabled = true

[storage]
enabled = true

[edge-functions]
[edge-functions.validate-auth-token]
verify_jwt = false
